apps:
  haproxy-ingress:
    namespace: haproxy-ingress
    chart: haproxy-ingress
    repo: https://haproxy-ingress.github.io/charts
    targetRevision: ">=0-0"
    path: ./
    type: helm
  cert-manager:
    namespace: cert-manager
    chart: cert-manager
    targetRevision: ">=0-0"
    repo: https://charts.jetstack.io
    type: helm
    parameters:
      installCRDs: true
  argocd:
    namespace: argocd
    chart: argo-cd
    repo: https://argoproj.github.io/argo-helm
    targetRevision: ">=0-0"
    path: ./
    type: helm
  argocd-apps:
    namespace: argocd
    chart: argocd-apps
    repo: https://argoproj.github.io/argo-helm
    targetRevision: ">=0-0"
    path: ./
    type: helm
  kubernetes-dashboard:
    namespace: kubernetes-dashboard
    chart: kubernetes-dashboard
    repo: https://kubernetes.github.io/dashboard/
    targetRevision: ">=0-0"
    path: ./
    type: helm