{{- range $name, $v :=  .Values.apps }}
---
apiVersion: v1
data:
  name: {{$name |b64enc }}
  project: ZGVmYXVsdA==
  type: aGVsbQ==
  url: {{$v.repo |b64enc}}
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: {{$name}}
  namespace: argocd
type: Opaque
{{- end }}
